version: '3'
services:
  
  backend:
    image: "varunmargam/flask-todo-app-cicd"  # Use the image from DockerHub
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER: varun
      MYSQL_PASSWORD: varun@123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
